### ISSUE TITLE
Adding Helical to line

### ISSUE THREAD

**Issue by bolmsten** [mxcube/mxcubeweb#435]
We had this feature before but removed and now it is only possible to create while selecting two points. I think there might be a need for it to return as I saw many people expecting it to be there on a right click.

**Comment by mguijarr** [comment]
To my knowledge, the feature to have is:
- user makes some centered positions, when user does a right click the context menu is shown, if more than 1 point is selected there is a `Helical` entry, lines are drawn between two points (if `A`, `B`, `C` points are selected it would produce 2 lines, from `A` to `B` and `B` to `C`, ie. 2 helicals)

**Comment by marcus-oscarsson** [comment]
Outdated
