### ISSUE TITLE
Disable unavailable params in modals

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcubeweb#512]
The task configuration modal allows to write into all parameters even if they are not available in the beamline.

The modal should check in the state for available actuators/movables and disable the input fields for the ones missing (or a better way)

**Comment by marcus-oscarsson** [comment]
Is this one completely done ?

**Comment by meguiraun** [comment]
not really. I was thinking on something like this https://github.com/mxcube/mxcube3/pull/704

I will extend and submit a full pr soon

**Comment by marcus-oscarsson** [comment]
What was the progress on this ?

**Comment by marcus-oscarsson** [comment]
Done
