### ISSUE TITLE
"Select Proposal" form not showing for user login type

### ISSUE THREAD

**Issue by laispc** [mxcube/mxcubeweb#874]
* **How to reproduce**:

In the current master (using the mockup config), when loginType is switched to "user", I get the following error after pressing the "Sign in" button:

```
MX3.HWR|INFO   | [LOGIN] User idtest0 could not login (string indices must be integers)
```

* **Trying to fix**

The cause seems to be the fact the "Session" is not a list anymore in proposal dictionary. If I set "Session" as list again just to make Python happy, the error stops. However, after pressing "Sign in", I got a blank page instead of the expected "Select Proposal" form and no error is shown in the terminal/log.

Any ideas? Thanks!

* **Context**

The mxcube3 I am using has some frozen widgets, like the motor widgets (they can set values, but the current position is not updated automatically in the screen; they update only if I press F5). Testing the current master, I saw that they work fine, so my idea to rebase to the current master to use the fix. However, as I need "user" login type, when I switched that parameter I got the error above.

**Comment by meguiraun** [comment]
can you try changing
https://github.com/mxcube/mxcube3/blob/master/mxcube3/ui/components/Login/SelectProposal.js#L41
to 
`Session: prop.Session.startDate.split(' ')[0]
`
together with the session fix for making python happy.

This is definitely a place which need more care.
How do plan to use the selectproposal functionality? I wonder if we both have the same needs in the functionality

**Comment by meguiraun** [comment]
But it is a bit weird since I did no need to change that on my pr https://github.com/mxcube/mxcube3/pull/841

**Comment by laispc** [comment]
@meguiraun thanks for this! I wil test here asap and I will let you know.

**Comment by laispc** [comment]
@meguiraun I have being using this fix you proposed here during the week, and it is working really fine. Thanks a lot! :)
If this fix enters the master version, let me know if possible.

About SelectProposal, our current plan is to list all the proposals of the day (getting the info from the Users Portal) just after the user login, so he/she can choose the proposal to work on.
The login is done with their personal credentials (user.name + password), reusing the same credentials that the user already have for other systems in the lab.

Here, we do not have a login for proposals (proposal number + password). Instead, we created groups for the proposal. The user then can be made a member of a proposal group, so they can, for example, be granted access to the collected files in the storage and other security/permission routines.

The next step will be to filter the proposals shown in SelectProposal form, so the logged user will see only the proposals he/she is a member of.

I don know if I fully answered your question, so let me know if you need more details.
How about you? How have you used SelectProposal?

**Comment by laispc** [comment]
By the way, I noticed that, mxcube considers the proposal number (8 digits) plus an index (like 0).
For now I don't really know how/if I am going to use this index. In our context, we just consider the proposal number.
I guess it is for repeating the same proposal already done in the past.
Is it used by you?

**Comment by meguiraun** [comment]
We are using essentially the same flow as you, in our case a user can select from all of his/hers proposals (assuming they are open from the user office point of view, the list comes from Ispyb). They also login with the personal username, also, all members of the proposal are part of the same unix group so they all have access to the data.

I do not understand what you mean by " mxcube considers the proposal number (8 digits) plus an index (like 0).", can you point to the code? or some example?

**Comment by laispc** [comment]
> We are using essentially the same flow as you, in our case a user can select from all of his/hers proposals (assuming they are open from the user office point of view, the list comes from Ispyb). They also login with the personal username, also, all members of the proposal are part of the same unix group so they all have access to the data.

Nice. Essentially we are doing the same thing. We are missing the ISPyB part here, but we plan to integrate it in the next steps.

> I do not understand what you mean by " mxcube considers the proposal number (8 digits) plus an index (like 0).", can you point to the code? or some example?

Yes. For example, in Session class there is a method to get the proposal, which is formed by a code plus a number/index:

https://github.com/mxcube/HardwareRepository/blob/master/HardwareObjects/Session.py#L285

Here, we don't use this `self.proposal_number`, only the code, so I wonder if you use it and how.
Thanks!
